### ISSUE TITLE
Mask problem with export

### ISSUE THREAD

**Issue by roybarber** [airbnb/lottie#38]
Hi there, when exporting from AE i seem to have a problem with masks on a few elements, but then other elements are fine, a demo ive created here: https://lottie.netlify.com/
Any ideas on any specific settings or changes i would need to make?

**Comment by bodymovin** [comment]
hi, can you share the .aep?
Are you using illustrator layers converted to shapes?

**Comment by roybarber** [comment]
hey @bodymovin i can share the AEP privately, its supplied by my animator.

**Comment by roybarber** [comment]
@bodymovin i emailed you a link to the AEP

**Comment by bodymovin** [comment]
There is an issue when .ai layers are converted to shapes in AE.
In some cases (for example when the art in AI exceeds the Artboard), AE adds an extra Path and a Merge Path on every shape layer group.
Since Lottie-Web doesn't support merge paths, the animation looks broken.
If you delete the extra path, everything should look fine.
As an example in your animation, on the composition Sag_El -> S_E_Kıyafet Outlines 3 -> Contents -> Group 1
You should remove Merge Path and Path 2

**Comment by roybarber** [comment]
Thanks @bodymovin ill pass this on to my animator and request a new file.
