### ISSUE TITLE
Request: add Lottie plugin for Android-Studio

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [airbnb/lottie#73]
In order to show the json files , visually.
It should be able to show a single file when opening it, and it should be able to show a grid of all of them.
It could also be nice to have OS plugin, so that we could have a thumbnail shown for each.
I hope it's possible, because the more animations we have in an app, the harder it gets to manage them.
I also hope that Lottie has some kind of thumbnails support, to tell whoever that is about to show it as an image, which frame to use.

**Comment by gpeal** [comment]
@AndroidDeveloperLB It would be great it somebody in the community were to develop one. Unfortunately, I don't think that I could make time for that right now. You can use the macOS app on the [lottie-ios](https://github.com/airbnb/lottie-ios/) repo or preview animations on lottiefiles to help.

If you have a lot of animations, I also recommend using res/raw instead of asset names so you get static references to your animations so you can't make typos and can find usages/unused animations.

**Comment by AndroidDeveloperLB** [comment]
It's too bad. I remember even Google mentions Lottie on at least one of its lectures.

**Comment by gpeal** [comment]
@AndroidDeveloperLB Yeah, Google uses Lottie in *many* of its apps 😄 However, I don't think Android Studio has a full Skia renderer for views.

**Comment by AndroidDeveloperLB** [comment]
@gpeal Really? I wonder in which apps Google uses Lottie, and I also wonder if Google helps Lottie in some way...
